# Generated by Django 3.1.3 on 2020-11-11 11:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('namespace', models.CharField(max_length=120, unique=True, verbose_name='NameSpace')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
