# Generated by Django 3.1.3 on 2020-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='namespace',
            field=models.CharField(max_length=120, verbose_name='NameSpace'),
        ),
    ]
